services:
  flask-app:
    build: . # Uncomment this if you need to build 
    image: ghcr.io/tuanchris/dune-weaver:main # Use latest production image
    restart: always
    ports:
      - "80:8080" # Map port 8080 of the container to 80 of the host
    volumes:
      - ./patterns:/app/patterns # Map host folder to container folder
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    environment:
      - FLASK_ENV=development # Set environment variables for Flask
    container_name: flask-theta-rho-app
